### ISSUE TITLE
COMPETITION: Torpedo board

### ISSUE THREAD

**Issue by rleyva** [uf-mil/SubjuGator#145]
**Tasks to complete**
- [x] Torpedo board detection 
- [ ] Aligning to torpedo board 
- [ ] Actuating torpedo board cover
- [ ] Text recognition 
- [ ] Shooting torpedo

@LucasBA - You're still onboard with working on the text recognition, correct?

**Comment by LucasBA** [comment]
Yes, I was going to set it aside for a week and do the ball dropper mission for the crusade. I have python-tesseract ocr working pretty decently on my machine I need to rosify and test

**Comment by mattlangford** [comment]
Will reopen for this new year
